# Generated by Django 4.2.9 on 2025-03-01 13:08

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='photos',
        ),
        migrations.AddField(
            model_name='events',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='foto/'),
        ),
        migrations.AddField(
            model_name='events',
            name='style_background_color',
            field=colorfield.fields.ColorField(default='#DB0808', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='events',
            name='style_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='events',
            name='sub_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
