# Generated by Django 4.2.9 on 2025-03-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0002_remove_events_photos_events_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='events_photo/'),
        ),
    ]
