# Generated by Django 4.2.9 on 2025-03-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0003_alter_events_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.ImageField(upload_to='events_photo/'),
        ),
    ]
