# Generated by Django 4.2.9 on 2025-03-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0004_alter_events_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='map_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
