# Generated by Django 4.2.9 on 2025-03-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0005_events_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='state',
            field=models.CharField(choices=[('P', 'Pubblicato'), ('B', 'Bozza'), ('I', 'In corso'), ('C', 'Concluso'), ('A', 'Annullato')], default='B', max_length=1),
        ),
        migrations.DeleteModel(
            name='EventStatus',
        ),
    ]
