# Generated by Django 4.2.9 on 2025-03-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0006_alter_events_state_delete_eventstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='state',
            field=models.CharField(choices=[('?', 'In attesa approvazione idonietà'), ('G', 'Idonea'), ('B', 'Non idonea')], default='W', max_length=1),
        ),
        migrations.DeleteModel(
            name='CarStatus',
        ),
    ]
