# Generated by Django 4.2.9 on 2025-03-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0008_events_style_card_body_backgroud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='plate',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
