# Generated by Django 4.2.9 on 2025-03-15 17:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0009_alter_cars_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='style_background_color',
            field=colorfield.fields.ColorField(default='#DB0808', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='events',
            name='style_card_body_backgroud',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='events',
            name='style_card_body_btn_confirm_background',
            field=colorfield.fields.ColorField(default='#DB0808', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='events',
            name='style_card_body_btn_confirm_text',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='events',
            name='style_card_body_text',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='events',
            name='style_card_header_backgroud',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='events',
            name='style_card_header_text',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='events',
            name='style_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
