# Generated by Django 4.2.9 on 2025-03-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0010_alter_events_style_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='map_url_to_share',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='theme_pixel.carcategory'),
        ),
    ]
