# Generated by Django 4.2.9 on 2025-03-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0011_events_map_url_to_share_alter_cars_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='max_access',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='events',
            name='subscribe_close',
            field=models.BooleanField(default=False),
        ),
    ]
